name: Build Disports

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Clickable
        run: |
          docker pull clickable/ci-ut24.04-1.x-arm64:latest

      - name: Build
        run: |
          docker run \
            --env UV_INSTALL_DIR=/usr/local \
            --volume ./:/app \
            clickable/ci-ut24.04-1.x-arm64:latest \
            bash -c "cd /app && clickable build"

      - name: Upload click package
        uses: actions/upload-artifact@v4
        with:
          name: disports-${{ github.sha }}
          path: build/all/app/*.click
          retention-days: 30
